app_port: 8000
conf_balancer:
  normal_retries: 3
  timeout: 3ms
  rpc_nodes:
    - "https://mainnet.infura.io/v3/abc"
    - "https://drpc-eth-node-frnx-02.rpc.p2p.world/abc"
  rpc_fallback_nodes:
    - "https://rpc.ankr.com/eth/abc"